# Configuration for WPDistillery executed by setup.sh
#
# Author: Flurin Dürst
# URL: https://wpdistillery.org
#
# For detailed instructions on this file read the config.yml-documentation at
# https://wpdistillery.org/documentation/config-yml-documentation/
#
# File Version: 1.6.4


# INSTALLATION
#################################################################

# WordPress folder
wpfolder: public

# WordPress version
wpversion: latest

# language/timezone
wplocale: en_CA
timezone: "America/Vancouver"

# admin user settings
admin:
  user: launchpad
  password: launchpad2017
  email: launchpad@launchpad.test
  first_name: "Launchpad"
  last_name: "Admin"

# scotch box db access
db:
  name: scotchbox
  user: root
  pass: root
  prefix: wp_

# SETTINGS
#################################################################

wpsettings:
  url: launchpad.test
  title: Launchpad Website
  description: Template
  permalink_structure: "/%postname%/"
  thumbnail_width: 150
  thumbnail_height: 150
  medium_width: 300
  medium_height: 300
  large_width: 1024
  large_height: 1024
  # use page as frontpage
  page_on_front: true
  # define frontpage name (requires `page_on_front: true`)
  frontpage_name: Home
  # automatic conversion of smilies
  convert_smilies: false

# THEME
#################################################################

# theme to install, choose new name in 'rename' or leave empty
theme:
  name: WPSeed
  rename: ""
  url: "https://github.com/flurinduerst/WPSeed/archive/master.zip"

# PLUGINS
#################################################################

# plugins to install & activate
plugins_active:
  - disable-comments
  - duplicate-post
  - enable-media-replace
  - favicon-by-realfavicongenerator
  - regenerate-thumbnails
  - simple-page-ordering
  - user-switching
  - post-thumbnail-editor
  - wp-security-audit-log
  - bulk-page-creator
  - simple-301-redirects
  - simple-301-redirects-addon-bulk-uploader
  - "http://plugins.kanpachi.net/gravityforms/gravityforms_2.2.5.21.zip"
  - "http://plugins.kanpachi.net/gravityforms/gravityformsmailchimp_4.2.4.zip"
  - "http://plugins.kanpachi.net/site-analytics/site-analytics.zip"
  - "http://plugins.kanpachi.net/visualcomposer/js_composer-5.5.zip"
  - "http://plugins.kanpachi.net/templatera/templatera-2017-10-27.zip"
  - "http://plugins.kanpachi.net/acf/advanced-custom-fields-pro-5.6.7.zip"
  - wordpress-seo

# plugins to install
plugins_inactive:
  #development
  - custom-post-type-ui
  - better-search-replace
  - capability-manager-enhanced
  #administration
  - adminimize
  - admin-menu-editor
  - admin-menu-reorder
  # seo
  - autodescription

# WPDISTILLERY SETUP
####################################################################
# if you don't want the setup to run all tasks, set them to false

setup:
  wp: true
  settings: true
  theme: true
  plugins: true
  cleanup: true
  # adjust what data you want to be deleted within the cleanup (required `cleanup: true`)
  comment: true
  posts: true
  files: true
  themes: true
